import { Oswald, Oooh_Baby } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const ooohBaby = Oooh_Baby({
  weight: "400",
  variable: "--font-oooh-baby",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${ooohBaby.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
